from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class ExplorationAssets: 

	# Image Rule Assets
	# 第二十五章位置 
	I_EXP_CHAPTER_25 = RuleImage(
		roi=(1048, 196, 208, 103),
		area=(944, 144, 416, 206),
		file="./tasks/exploration/res/exp_25.png"
	)
	# 第二十八章位置（在最底下的时候） 
	I_EXP_CHAPTER_28 = RuleImage(
		roi=(1058, 493, 189, 94),
		area=(1011, 446, 268, 188),
		file="./tasks/exploration/res/exp_28.png"
	)
	# 探索困难模式按钮(已选) 
	I_EXP_HARD_BUTTON_CHECKED = RuleImage(
		roi=(417, 198, 101, 61),
		area=(366, 168, 202, 122),
		file="./tasks/exploration/res/exp_hard_button_checked.png"
	)
	# 探索困难模式按钮(未选) 
	I_EXP_HARD_BUTTON_UNCHECKED = RuleImage(
		roi=(433, 205, 74, 46),
		area=(396, 182, 148, 92),
		file="./tasks/exploration/res/exp_hard_button_unchecked.png"
	)
	# 取消章节探索 
	I_EXP_CHAPTER_DISMISS_ICON = RuleImage(
		roi=(1024, 129, 45, 45),
		area=(1002, 106, 90, 90),
		file="./tasks/exploration/res/exp_chapter_dismiss_icon.png"
	)
	# 自动轮换开启 
	I_AUTO_ROTATE_ON = RuleImage(
		roi=(104, 649, 153, 44),
		area=(28, 627, 306, 88),
		file="./tasks/exploration/res/auto_rotate_on.png"
	)
	# 自动轮换关闭 
	I_AUTO_ROTATE_OFF = RuleImage(
		roi=(108, 650, 150, 46),
		area=(33, 627, 300, 92),
		file="./tasks/exploration/res/auto_rotate_off.png"
	)
	# 探索队伍未锁定 
	I_EXP_TEAM_UNLOCK = RuleImage(
		roi=(898, 654, 17, 25),
		area=(890, 642, 34, 50),
		file="./tasks/exploration/res/exp_team_unlock.png"
	)
	# 探索队伍锁定 
	I_EXP_TEAM_LOCK = RuleImage(
		roi=(895, 651, 23, 30),
		area=(884, 636, 46, 60),
		file="./tasks/exploration/res/exp_team_lock.png"
	)
	# 探索章节退出确认 
	I_EXP_CHAPTER_EXIT_CONFIRM = RuleImage(
		roi=(689, 376, 172, 57),
		area=(603, 348, 344, 114),
		file="./tasks/exploration/res/exp_chapter_exit_confirm.png"
	)
	# 探索章节确认 
	I_EXP_BUTTON = RuleImage(
		roi=(881, 511, 129, 56),
		area=(816, 483, 258, 112),
		file="./tasks/exploration/res/exp_button.png"
	)
	# 探索怪物挑战图标 
	I_EXP_BATTLE = RuleImage(
		roi=(787, 270, 42, 41),
		area=(0, 0, 1276, 719),
		file="./tasks/exploration/res/exp_battle.png"
	)
	# 探索章节boss 
	I_EXP_BOSS = RuleImage(
		roi=(615, 250, 49, 44),
		area=(0, 0, 1276, 719),
		file="./tasks/exploration/res/exp_boss.png"
	)
	# 怪物奖励突破票掉落显示区域 
	I_EXP_REALM_RAID_TICKET = RuleImage(
		roi=(414, 179, 76, 91),
		area=(231, 153, 1000, 446),
		file="./tasks/exploration/res/exp_realm_raid_ticket.png"
	)
	# 探索发现物品栏(左) 
	I_EXP_TREASURE_BOX_LEFT = RuleImage(
		roi=(37, 203, 65, 35),
		area=(4, 186, 135, 320),
		file="./tasks/exploration/res/exp_treasure_box.png"
	)
	# 困28探索界面宝箱区域 
	I_EXP_TREASURE_BOX_MAP = RuleImage(
		roi=(37, 203, 65, 35),
		area=(670, 210, 130, 90),
		file="./tasks/exploration/res/exp_treasure_box.png"
	)
	# 获得奖励栏标 
	I_EXP_GAIN_REWARD = RuleImage(
		roi=(476, 233, 329, 42),
		area=(312, 212, 658, 84),
		file="./tasks/exploration/res/exp_gain_reward.png"
	)
	# 探索章节内发现物品 
	I_EXP_CHAP_REWARD = RuleImage(
		roi=(635, 489, 33, 21),
		area=(430, 300, 450, 300),
		file="./tasks/exploration/res/exp_chap_reward.png"
	)
	# 章节内小标志 
	I_EXP_C_CHAPTER = RuleImage(
		roi=(26, 555, 29, 45),
		area=(12, 541, 57, 73),
		file="./tasks/exploration/res/exp_c_chapter.png"
	)

	# Ocr Rule Assets
	# 探索界面突破票数量 
	O_EXP_VIEW_TICKET_COUNT = RuleOcr(
		roi=(741, 15, 71, 27),
		area=(741, 15, 71, 27),
		name="exp_view_ticket_count"
	)
	# 探索界面章节入口开启后突破票数量 
	O_EXP_CHAPTER_TICKET_COUNT = RuleOcr(
		roi=(940, 16, 73, 27),
		area=(940, 16, 73, 27),
		name="exp_chapter_ticket_count"
	)


	# Swipe Rule Assets
	# 向上滑动章节 
	S_EXP_LEVEL_UP = RuleSwipe(
		roi_start=(1047, 549, 1256, 656),
		roi_end=(1048, 196, 1256, 299),
		name="exp_level_up"
	)
	# 向下滑动章节 
	S_EXP_LEVEL_DOWN = RuleSwipe(
		roi_start=(1048, 196, 1256, 299),
		roi_end=(1047, 549, 1256, 656),
		name="exp_level_down"
	)
	# 往左滑动,往右走 
	S_EXP_TO_RIGHT = RuleSwipe(
		roi_start=(700, 200, 900, 500),
		roi_end=(150, 200, 500, 500),
		name="exp_to_right"
	)
	# 往右滑动,往左走 
	S_EXP_TO_LEFT = RuleSwipe(
		roi_start=(200, 200, 600, 500),
		roi_end=(800, 200, 900, 500),
		name="exp_to_left"
	)


