from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class MinamotoAssets: 

	# Image Rule Assets
	# 队伍锁定 
	I_TEAM_LOCK = RuleImage(
		roi=(823, 650, 22, 28),
		area=(812, 639, 44, 50),
		file="./tasks/minamoto/res/team_lock.png"
	)
	# 队伍不锁定 
	I_TEAM_UNLOCK = RuleImage(
		roi=(825, 652, 17, 23),
		area=(817, 644, 33, 39),
		file="./tasks/minamoto/res/team_unlock.png"
	)
	# 鬼兵演武挑战 
	I_GHOST_CHALLENGE = RuleImage(
		roi=(1128, 582, 103, 85),
		area=(1086, 540, 187, 169),
		file="./tasks/minamoto/res/ghost_challenge.png"
	)
	# 兵藏秘境挑战 
	I_BING_CHALLENGE = RuleImage(
		roi=(1125, 586, 108, 77),
		area=(1087, 548, 184, 153),
		file="./tasks/minamoto/res/bing_challenge.png"
	)
	# 鬼兵演武入口 
	I_GHOST_ENT = RuleImage(
		roi=(93, 340, 42, 136),
		area=(72, 319, 84, 178),
		file="./tasks/minamoto/res/ghost_ent.png"
	)
	# 兵藏秘境入口 
	I_BING_ENT = RuleImage(
		roi=(1087, 346, 43, 134),
		area=(1065, 324, 87, 178),
		file="./tasks/minamoto/res/bing_ent.png"
	)

	# Ocr Rule Assets
	# 鬼兵部等级 
	O_GHOST_LEVEL = RuleOcr(
		roi=(144, 495, 38, 22),
		area=(144, 495, 38, 22),
		keyword="",
		name="ghost_level"
	)


