from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class RoyalBattleAssets: 
	pass

