from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class ShikigamiActivityAssets: 


	# Click Rule Assets
	# left 
	C_SA_REWARD_LEFT = RuleClick(roi=(40, 80, 220, 660), area=(40, 80, 220, 660), name="sa_reward_left")
	# bottom 
	C_SA_REWARD_BOTTOM = RuleClick(roi=(30, 600, 1200, 100), area=(30, 600, 1200, 100), name="sa_reward_bottom")
	# right 
	C_SA_REWARD_RIGHT = RuleClick(roi=(1010, 80, 250, 620), area=(1010, 80, 250, 620), name="sa_reward_right")

	# Image Rule Assets
	# 庭院活动入口 
	I_SA_ENT = RuleImage(
		roi=(378, 172, 50, 37),
		area=(300, 134, 206, 113),
		file="./tasks/shikigami_activity/res/sa_ent.png"
	)
	# 爬塔入口 
	I_SA_FIGHT_ENT = RuleImage(
		roi=(896, 205, 33, 158),
		area=(880, 189, 65, 190),
		file="./tasks/shikigami_activity/res/sa_fight_ent.png"
	)
	# 活动页面确认 
	I_SA_CHECK = RuleImage(
		roi=(91, 14, 180, 44),
		area=(69, 0, 224, 88),
		file="./tasks/shikigami_activity/res/sa_check.png"
	)
	# 爬塔页面确认 
	I_SA_FIGHT_CHECK = RuleImage(
		roi=(88, 17, 173, 40),
		area=(68, 0, 213, 80),
		file="./tasks/shikigami_activity/res/sa_fight_check.png"
	)
	# 使用体力 
	I_SA_EP = RuleImage(
		roi=(1127, 505, 34, 29),
		area=(1113, 491, 62, 57),
		file="./tasks/shikigami_activity/res/sa_ep.png"
	)
	# 使用爬塔门票 
	I_SA_TICKET = RuleImage(
		roi=(1126, 509, 35, 23),
		area=(1114, 497, 59, 47),
		file="./tasks/shikigami_activity/res/sa_ticket.png"
	)
	# 体力门票转换 
	I_SA_SWITCH = RuleImage(
		roi=(1223, 508, 28, 27),
		area=(1209, 494, 56, 55),
		file="./tasks/shikigami_activity/res/sa_switch.png"
	)
	# 队伍不锁定 
	I_SA_TEAM_UNLOCK = RuleImage(
		roi=(806, 650, 17, 24),
		area=(798, 642, 33, 40),
		file="./tasks/shikigami_activity/res/sa_team_unlock.png"
	)
	# 队伍锁定 
	I_SA_TEAM_LOCK = RuleImage(
		roi=(805, 649, 18, 26),
		area=(796, 640, 36, 44),
		file="./tasks/shikigami_activity/res/sa_team_lock.png"
	)
	# 战斗 
	I_SA_FIGHT = RuleImage(
		roi=(1124, 589, 102, 83),
		area=(1082, 547, 186, 167),
		file="./tasks/shikigami_activity/res/sa_fight.png"
	)
	# 退出 
	I_SA_EXIT = RuleImage(
		roi=(20, 16, 42, 41),
		area=(0, 0, 82, 81),
		file="./tasks/general/res/buttons/b_yellow_left_angle.png"
	)
	# 没票了 
	I_SA_NO_TICKETS = RuleImage(
		roi=(675, 27, 135, 26),
		area=(662, 14, 161, 52),
		file="./tasks/shikigami_activity/res/sa_no_tickets.png"
	)
	# 获得奖励 
	I_SA_GAIN_REWARD = RuleImage(
		roi=(476, 233, 329, 42),
		area=(400, 160, 500, 170),
		file="./tasks/general/res/gain_reward.png"
	)
	# 胜利 
	I_SA_BATTLE_WIN = RuleImage(
		roi=(411, 122, 172, 129),
		area=(347, 58, 300, 257),
		file="./tasks/battle/res/battle_win.png"
	)

	# Ocr Rule Assets
	# 爬塔门票数量 
	O_TICKET_COUNT = RuleOcr(
		roi=(711, 26, 99, 28),
		area=(711, 26, 99, 28),
		keyword="",
		name="ticket_count"
	)
	# 五倍卷数量 
	O_FIVEFOLD_COUNT = RuleOcr(
		roi=(944, 24, 65, 32),
		area=(944, 24, 65, 32),
		keyword="",
		name="fivefold_count"
	)


